yugabyte/yb-sample-apps

Dockerfile, README.md, pom.xml
Adding the option to generate docker image out of yb-sample-apps and publish it to dockerhub
Run package command to build and generate the docker image locally
`mvn package`
To just package without generating the docker image you need to run
`mvn package -DskipDockerBuild`
You can run following command to publish to our docker hub registry.
`docker push yugabytedb/yb-sample-apps:<version>` 
To run the sample apps in background
`docker run -id yugabytedb/yb-sample-apps:1.0 --workload CassandraKeyValue --nodes <node ips>`
=> Add Dockerfile for sample apps and enable publishing

.gitignore, src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/CassandraBatchKeyValue.java, src/main/java/com/yugabyte/sample/apps/CassandraBatchTimeseries.java, src/main/java/com/yugabyte/sample/apps/CassandraKeyValueBase.java, src/main/java/com/yugabyte/sample/apps/CassandraPersonalization.java, src/main/java/com/yugabyte/sample/apps/CassandraSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/CassandraStockTicker.java, src/main/java/com/yugabyte/sample/apps/CassandraTimeseries.java, src/main/java/com/yugabyte/sample/apps/CassandraTransactionalKeyValue.java, src/main/java/com/yugabyte/sample/apps/CassandraTransactionalRestartRead.java, src/main/java/com/yugabyte/sample/apps/CassandraUniqueSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/RedisHashPipelined.java, src/main/java/com/yugabyte/sample/apps/RedisKeyValue.java, src/main/java/com/yugabyte/sample/apps/RedisPipelinedKeyValue.java, src/main/java/com/yugabyte/sample/apps/RedisYBClientKeyValue.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java, src/main/java/com/yugabyte/sample/apps/SqlSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/SqlSnapshotTxns.java, src/main/java/com/yugabyte/sample/apps/SqlUpdates.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java, src/main/java/com/yugabyte/sample/common/SimpleLoadGenerator.java
General, all apps are now idempotent (i.e. can be run multiple times and will clean up output of old runs before starting).
`SqlInserts`: Enable bind variables for reads.
`SqlUpdates`: Now requires SqlInserts to run first, will then update those keys. Added new required arguments and updated help doc accordingly. 
`SqlSecondaryIndex` and `SqlSnapshotTxns`: Fix some syntax issues and update default args.
=> Misc fixes to YSQL sample apps

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
With YB universes not supporting insecure connections any more, the sample apps need to allow SSL connections to the cassandra query client.
Tested by running a sample app targeted to a universe with the following command:
```java -jar target/yb-sample-apps.jar --workload CassandraKeyValue --nodes 172.151.38.166:9042 --ssl_cert /opt/yugaware/certs/f33e3c9b-75ab-4c30-80ad-cba85646ea39/91ebf773-647d-4ba9-8736-7f077fefb681/ca.root.crt```
Also verified that is failed when no cert was provided.
Addressed issue: https://github.com/YugaByte/yugabyte-db/issues/1061
=> Add SSL support for YCQL connections.

src/main/java/com/yugabyte/sample/apps/CassandraBatchTimeseries.java
The default setting for CassandraBatchTimeseries only creates 10 metrics, which causes a huge skew in the tablet sizes, unless one specifies `--min_metrics_count 10000 --max_metrics_count 20000`
Bumping up the defaults so that we create 10000 metrics by default. Unless overridden by commandline flags.
=> Increase the defaults for num_metrics in CassandraBatchTimeseries

src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/CassandraBatchKeyValue.java, src/main/java/com/yugabyte/sample/apps/CassandraBatchTimeseries.java, src/main/java/com/yugabyte/sample/apps/CassandraEventData.java, src/main/java/com/yugabyte/sample/apps/CassandraSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
Add SQLDataLoad as a configurable sample app for benchmarking data loading into an YSQL table.
It allows configuring the number of columns, indexes, foreign keys, write-threads, batch size, etc.
See `java -jar target/yb-sample-apps.jar --help SqlDataLoad` for more details.
Examples:
- Table with `100` columns, using batch size `10` (`16` write threads).
```
java -jar target/yb-sample-apps.jar --workload SqlDataLoad --nodes 127.0.0.1:5433 \ 
--num_threads_write 16 --num_value_columns 100 --batch_size 10
```
- Table with `2` indexes and `1` foreign key (`8` write threads).
```
java -jar target/yb-sample-apps.jar --workload SqlDataLoad --nodes 127.0.0.1:5433 \
--num_threads_write 8 --num_indexes 2  --num_foreign_keys 1 
```
=> Add SqlDataLoad sample app

src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
Tested the following command lines to verify the parsing
`java -jar target/yb-sample-apps.jar --nodes foo5433 --workload SqlInserts`
(got exception)
`java -jar target/yb-sample-apps.jar --nodes [2600:1f18:1094:c832:36e6:43b9:e6c8:f02]:5433 --workload SqlInserts`
(works correctly and earlier did not work correctly)
and regular DNS, IPv4 addresses
(worked always)
=> Fix parsing of IPv6 contact points

src/main/java/com/yugabyte/sample/apps/CassandraInserts.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java, src/main/java/com/yugabyte/sample/common/SimpleLoadGenerator.java
Summary:
This new workload allows us to create a table with a varying number of
indexes and perform reads/writes to it. The number of indexes is
configured using 'num_indexes'
The value size is also configurable using `value_size`
Example:
java -jar target/yb-sample-apps.jar --workload CassandraInserts  \
--nodes 127.0.0.1:9042 --value_size 20 --num_indexes 2
Reviewers:
Mikhail, Neha, Mihnea
=> Cassandra multi index workload.

src/main/java/com/yugabyte/sample/apps/AppBase.java
The default consistency used by YugabyteDB is QUORUM (for reads and writes).
However, when this tool is used against say Apache Cassandra, where the default is ONE, then the comparison becomes apples to oranges. 
To avoid the confusion, just explicitly set the consistency level to QUORUM.
=> Change default consistency level to QUORUM

src/main/java/com/yugabyte/sample/Main.java, src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/MultiTableMultiIndexInserts.java, src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/apps/SqlForeignKeysAndJoins.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java, src/main/java/com/yugabyte/sample/apps/SqlSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/SqlSnapshotTxns.java, src/main/java/com/yugabyte/sample/apps/SqlUpdates.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
Currently applications such as SqlInserts and SqlSecondaryIndex do not drop existing table in createTablesIfNeeded().
This PR changes the behavior where by default, the table would be truncated in createTablesIfNeeded().
A flag, keep_table (without argument), is added. When the flag is specified, the table would be kept (and not truncated).
This is to facilitate simultaneous runs of the same application against the same DB table.
=> Add flag to keep table at application launch

src/main/java/com/yugabyte/sample/Main.java, src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/SqlUpdates.java, src/main/java/com/yugabyte/sample/apps/SqlUpdatesWithProcedures.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java, src/main/java/com/yugabyte/sample/common/SimpleLoadGenerator.java
Adding a new workload that is similar to `SqlUpdates` but that uses sql procedures in order to batch the updates together (see batching of updates in https://github.com/yugabyte/yugabyte-db/issues/5257).
=> Adding SqlUpdatesWithProcedures

pom.xml, src/main/java/com/yugabyte/sample/apps/AppBase.java
Use the `--local_reads` option to enable read from followers for any SQL sample app.
This will set the `yb_read_from_followers` session variable to true for every SQL connection.
For instance, for `SqlInserts` use:
```
java -jar target/yb-sample-apps.jar --workload SqlInserts --nodes 127.0.0.3:5433 --local_reads
```
Note: If testing locally using `yb-ctl` make sure to set the placement info so that routing can identify the local/remote nodes.
For instance, run `yb-ctl` as follows:
```
/bin/yb-ctl create --rf 3 --placement_info "cloud1.region1.zone1,cloud2.region2.zone2,cloud3.region3.zone3"
```
=> Add local_reads option for SQL apps

src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/SqlGeoPartitionedTable.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
Adds a new sample app based on SqlInserts but using a geo-partitioned table.
It creates a list-partitioned table with an additional primary-key column
'region', and a configurable number of partitions.
The value(s) for the new column (region) is automatically generated for each,
read/write operation based on the randomly-generated key column ('k').
Can be used with, for instance:
```
java -jar target/yb-sample-apps.jar --workload SqlGeoPartitionedTable --nodes 127.0.0.1:5433 --num_partitions 5
```
Which will generate the following table schema:
```
Table "public.sqlgeopartitionedtable"
Column | Type | Collation | Nullable | Default | Storage  | Stats target | Description
--------+------+-----------+----------+---------+----------+--------------+-------------
region | text |           | …
```
=> Add SqlGeoPartitionedTable app

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/apps/SqlForeignKeysAndJoins.java, src/main/java/com/yugabyte/sample/apps/SqlGeoPartitionedTable.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java, src/main/java/com/yugabyte/sample/apps/SqlSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/SqlSnapshotTxns.java, src/main/java/com/yugabyte/sample/apps/SqlUpdates.java
Operations in Sql classes such as SqlInserts would keep retrying upon connection errors.
Start SqlInserts workload of the sample app against a running local cluster, then stop some TS process (which the sample app connects to) in the local cluster (the cluster as a whole is still available), and the sample app resumes normal operations by getting connection to running TS.
=> Reconnect sql when current connection has error

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java, src/main/java/com/yugabyte/sample/common/metrics/JsonStatsMetric.java, src/main/java/com/yugabyte/sample/common/metrics/MetricsTracker.java, src/main/java/com/yugabyte/sample/common/metrics/Observation.java, src/main/java/com/yugabyte/sample/common/metrics/ReadableStatsMetric.java, src/main/java/com/yugabyte/sample/common/metrics/StatsTracker.java, src/main/java/com/yugabyte/sample/common/metrics/ThroughputObserver.java, src/main/java/com/yugabyte/sample/common/metrics/ThroughputStats.java
Add --output_json_metrics flag to trigger parseable json metrics to be logged when running sample apps.
Example:
```
$ java -jar yb-sample-apps.jar --workload SqlSecondaryIndex --nodes $IPS --num_threads_read 2 --num_threads_write 2 --num_unique_keys 1000000
...
14875 [Thread-1] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - Read: 939.51 ops/sec (1.95 ms/op), 4712 total ops  |  Write: 236.51 ops/sec (8.38 ms/op), 1183 total ops  |  Uptime: 5019 ms |
14901 [Thread-1] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - <json>{"Read":{"latency":{"mean":1954115.1034994684,"variance":4.01113298862315E13,"sampleSize":471
5,"min":938633.0,"max":2.73514324E8,"p99":1057826.166},"throughput":{"mean":1020.25,"variance":9037.583333333334,"sampleSize":4,"min":918.0,"max":1148.0,"p99":9 …
```
=> Add flag to output parseable json metrics

src/main/java/com/yugabyte/sample/common/metrics/JsonStatsMetric.java, src/main/java/com/yugabyte/sample/common/metrics/Observation.java
Previously, when running the following command:
java -jar target/yb-sample-apps.jar --workload CassandraKeyValue  --nodes 127.0.0.1:9042 --output_json_metrics
we would see output like:
6792 [Thread-2] INFO com.yugabyte.sample.common.metrics.MetricsTracker  - <json>{"Read":{"latency":{"mean":1484043.161940312,"variance":2.5166510662849356E11,"sampleSize":69186,"min":431077.0,"max":1.1387635E7,"p99":693622.5617},"throughput":{"mean":13280.0,"variance":1.1659124666666666E7,"sampleSize":4,"min":8262.0,"max":15920.0,"p99":8262.0}},"Write":{"latency":{"mean":1870880.7887033205,"variance":5.208910299786783E11,"sampleSize":5329,"min":516879.0,"max":1.131751E7,"p99":807463.768},"throughput":{"mean":1055.4,"variance":49592.8,"sampleSize":5,"min":895.0,"max":1430.0,"p99":895.0}}}</json>
Note that …
=> Output latency metrics in millis

src/main/java/com/yugabyte/sample/common/metrics/StatsTracker.java
Based on docs for DescriptiveStats, we need to pass in the percentile in (0,100]. Previously we were erroneously calling with .99, when we should be calling with 99.
See: https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/stat/descriptive/DescriptiveStatistics.html#getPercentile(double)
=> Fix p99 statistic calculation

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
Summary:
Enabling TLS connections need the server key and server cert files to be
passed as arguments:
java -jar target/yb-sample-apps.jar \
--workload SqlInserts \
--nodes ip1 \
--ssl_key /home/centos/yugabytedb.key.der \
--ssl_cert /home/centos/yugabytedb.crt
The key needs to be in the binary DER format instead of the pem
format which can be done as follows:
openssl pkcs8 -topk8 -inform PEM -in yugabytedb.key -outform DER -out yugabytedb.key.der  -v1 PBE-MD5-DES -nocrypt
Reviewers:
Mihnea
=> Allowing TLS connections from yb-sample-apps to postgres.

README.md
@kmuthukk reported the download link not working.
This PR appends the version to the jar name.
=> Fix URL for download link

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/CassandraBatchTimeseries.java, src/main/java/com/yugabyte/sample/apps/CassandraEventData.java, src/main/java/com/yugabyte/sample/apps/CassandraKeyValueBase.java, src/main/java/com/yugabyte/sample/apps/CassandraPersonalization.java, src/main/java/com/yugabyte/sample/apps/CassandraStockTicker.java, src/main/java/com/yugabyte/sample/apps/CassandraTimeseries.java, src/main/java/com/yugabyte/sample/apps/SqlForeignKeysAndJoins.java
Using a local reference object to avoid possible race conditions between different threads trying to create preparedInserts, preparedSelects etc and the resetClients and destroyClients methods.
=> Fixes a race condition between a getter method and reset/destroy methods

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java
We have the following exception handling code:
```
} catch (Exception e) {
...
preparedInsert = null;
```
The preparedInsert should be closed before nullifying.
The connection from which the prepared statement originates is also closed.
=> Close PreparedStatement as part of exception handling

src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/SqlGeoPartitionedTable.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
This patch modifies SqlGeoPartitioned workflow to use tablespaces. Now the app will associate each partition with a tablespace
It introduces 3 new options. Either the input provides:
--tablespaces : A new flag that provides a comma separated string with list of tablespaces to be used by the app.
(or)
--replication_factor and --placement_policies. The former specifies the RF for each tablespace. The latter is a comma separated list of cloud.region.zone strings. Each cloud.region.zone will be used to create a tablespace.
=> [WIP] SqlGeoPartitioned App must now work with Tablespaces

src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/apps/SqlGeoPartitionedTable.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java
Fixed couple apps so that they will only try to drop tables if they don't already exist. This was causing issues with repeated runs of yb-sample-apps.
=> Drop YSQL tables only if they don't exist

pom.xml, src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/apps/SqlForeignKeysAndJoins.java, src/main/java/com/yugabyte/sample/apps/SqlGeoPartitionedTable.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java, src/main/java/com/yugabyte/sample/apps/SqlSecondaryIndex.java, src/main/java/com/yugabyte/sample/apps/SqlSnapshotTxns.java, src/main/java/com/yugabyte/sample/apps/SqlUpdates.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
Added a command line option for Sql* workloads called '--load_balance'.
By default it will be 'true'. But can be switched off by providing _--load_balance false_ in the command line arg
Modified the pom.xml to point to Yugabyte JDBC driver.
Ran the Sql payloads and seems to be working as expected.
=> Integrated the jdbc smart driver with Sql* sample apps.

pom.xml
Changed pom.xml to point to the new jdbc-yugabyte jar which has
this issue fixed: https://github.com/yugabyte/yugabyte-db/issues/10894
After the fix the SqlInserts workload was run and both the numbers with and without load-balance were at par.
Details of the issue mention in PR: https://github.com/yugabyte/pgjdbc/pull/4
=> [YSQL SMART DRIVER] Fix for performance issue - https://github.com/yugabyte/pgjdbc/pull/4

pom.xml
Fixes SQL generated in PgResultSet.refresh() to escape column identifiers so as to prevent SQL injection.
Previously, the column names for both key and data columns in the table were copied as-is into the generated
SQL. This allowed a malicious table with column names that include statement terminator to be parsed and
executed as multiple separate commands.
CVE-2022-31197
=> Upgrade postgresql jdbc to 42.5.0

pom.xml, src/main/java/com/yugabyte/sample/common/metrics/Metric.java, src/main/java/com/yugabyte/sample/common/metrics/MetricsTracker.java
In current version we accumulate JSON metrics even if we don't print them. This will cause problems if we use Cassandra workloads with lots of operations, this leads to lots of data in memory and out of memory exception.
This fix will enable data collecting only if `output_json_metrics` flag is set to true
=> Fixed OOM for json metrics output

src/main/java/com/yugabyte/sample/Main.java, src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/CassandraKeyValue.java, src/main/java/com/yugabyte/sample/apps/CassandraKeyValueBase.java, src/main/java/com/yugabyte/sample/apps/SQLAppBase.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java
- Enable row count validation for `SqlInserts` and YCQL workloads that extend from `CassandraKeyValue`.
- Introduced a new abstract class for YSQL workloads - `YSQLAppBase` - so that the YSQL specific behaviour can be moved to one place.
- If the row count validation fails, a FATAL statement is logged but the workload is allowed to continue.
=> Enable row count validation for SqlInserts and YCQL workloads

src/main/java/com/yugabyte/sample/apps/AppBase.java
Log at info level instead of throwing UnsupportedOperationException in `AppBase`.
The workloads which do not override the methods `verifyTotalRowsWritten` and `recordExistingRowCount` were failing with message `"Row count check is not supported for this workload"`.
Now `AppBase` simply logs it at info level.
=> Log at info level instead of throwing UnsupportedOperationException

src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java, src/main/java/com/yugabyte/sample/apps/SqlForeignKeysAndJoins.java, src/main/java/com/yugabyte/sample/apps/SqlGeoPartitionedTable.java, src/main/java/com/yugabyte/sample/apps/SqlInserts.java, src/main/java/com/yugabyte/sample/apps/SqlSnapshotTxns.java
**Problem:**
The YSQL sample app insert workloads today cannot be executed indefinitely in the long running  universes, since they fill the disk up and we either need to add more storage to the test universes which has cost implications or we must stop the workloads, drop tables and restart them which no longer makes the test long running since there is an interruption involved. 
**Solution:**
Set the flag `yb_enable_upsert_mode` to true for each of these workloads.
Caveat:
This flag does not work for workloads with secondary index. Filed a [ticket](https://yugabyte.atlassian.net/browse/DB-7848) for the same. 
Note:
The workload SqlUpdates does not require any change because it runs only update command and no inserts. Inserts are done via SQLInserts for SQLUpdates workloads.
[Performance …
=> Incorporate option to execute write YSQL sample app workloads indefinitely with upserts

README.md, src/main/java/com/yugabyte/sample/Main.java, src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/apps/SqlStaleReadDetector.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java, src/main/java/com/yugabyte/sample/common/IOPSThread.java, src/main/java/com/yugabyte/sample/common/Throttler.java, src/main/java/com/yugabyte/sample/common/metrics/PromMetrics.java
YugabyteDB provides _read-after-commit-visibility_ guarantee as described by the `read restart error` section in Yugabyte Docs.  This guarantee prevents the stale read anomaly and we need a mechanism to detect stale reads. Moreover, several optimizations are introduced into the database to reduce the number of `read restart error`s, and it is desirable to have benchmarks that demonstrate these improvements.
1. A stale read detector app.
2. A mechanism to throttle read and write throughput.
3. A mechanism to execute read and write operations in lock step.
4. Collector for read restart prom metrics.
5. Cosmetic changes: use console style in the README, use YSQL where I could in comments.
To reproduce stale reads,
1. Limit hybrid time propagation.
a. Use replication_factor=1
b. Use a single …
=> [#22537] YSQL: Benchmark restart read requests metric.

src/main/java/com/yugabyte/sample/apps/AppBase.java
PG15 changed the permissions and [revokes the CREATE permission from all users](https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS) except a database owner from the public (or default) schema. This reults in the error: `ERROR: permission denied for schema public` while creating a table from the app when the user is not postgres or yugabyte.
This change is to grant the user create permissions from the app itself. 
Testing:
To test, create a new role on your cluster:
```
create role admin login password 'admin';
```
Run the yb-sample-apps and it should not give any error during create table
=> Grant permission to roles to create table on public schema

src/main/java/com/yugabyte/sample/apps/AppBase.java, src/main/java/com/yugabyte/sample/apps/AppConfig.java, src/main/java/com/yugabyte/sample/common/CmdLineOpts.java
This is a fix for PR #100 
For auth enabled cluster, implemented a command line option `yugabyte_password`, which is the password for the user yugabyte, that should be passed when the username is not `postgres` or `yugabyte` and auth is enabled for `yugabyte` user.
Also bug fix: Changed the condition from || to &&.
=> Grant permission to public schema fix for auth enabled cluster
